// ------------------------------------------------------------------------------
// <auto-generated>
// Este código fue generado por una herramienta.
// Versión del motor en tiempo de ejecución:2.0.50727.3655
// 
// Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
// se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=2.0.50727.3038.
// 

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/ine")]
[XmlRoot(Namespace = "http://www.sat.gob.mx/ine", IsNullable = false)]
public partial class INE
{
    private INEEntidad[] entidadField;
    private string versionField;
    private INETipoProceso tipoProcesoField;
    private INETipoComite tipoComiteField;
    private bool tipoComiteFieldSpecified;
    private int idContabilidadField;
    private bool idContabilidadFieldSpecified;

    public INE() : base()
    {
        versionField = "1.0";
    }

    /// <comentarios/>
    [XmlElement("Entidad")]
    public INEEntidad[] Entidad
    {
        get
        {
            return entidadField;
        }

        set
        {
            entidadField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string Version
    {
        get
        {
            return versionField;
        }

        set
        {
            versionField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public INETipoProceso TipoProceso
    {
        get
        {
            return tipoProcesoField;
        }

        set
        {
            tipoProcesoField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public INETipoComite TipoComite
    {
        get
        {
            return tipoComiteField;
        }

        set
        {
            tipoComiteField = value;
        }
    }

    /// <comentarios/>
    [XmlIgnore()]
    public bool TipoComiteSpecified
    {
        get
        {
            return tipoComiteFieldSpecified;
        }

        set
        {
            tipoComiteFieldSpecified = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public int IdContabilidad
    {
        get
        {
            return idContabilidadField;
        }

        set
        {
            idContabilidadField = value;
        }
    }

    /// <comentarios/>
    [XmlIgnore()]
    public bool IdContabilidadSpecified
    {
        get
        {
            return idContabilidadFieldSpecified;
        }

        set
        {
            idContabilidadFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/ine")]
public partial class INEEntidad
{
    private INEEntidadContabilidad[] contabilidadField;
    private t_ClaveEntidad claveEntidadField;
    private INEEntidadAmbito ambitoField;
    private bool ambitoFieldSpecified;

    /// <comentarios/>
    [XmlElement("Contabilidad")]
    public INEEntidadContabilidad[] Contabilidad
    {
        get
        {
            return contabilidadField;
        }

        set
        {
            contabilidadField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public t_ClaveEntidad ClaveEntidad
    {
        get
        {
            return claveEntidadField;
        }

        set
        {
            claveEntidadField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public INEEntidadAmbito Ambito
    {
        get
        {
            return ambitoField;
        }

        set
        {
            ambitoField = value;
        }
    }

    /// <comentarios/>
    [XmlIgnore()]
    public bool AmbitoSpecified
    {
        get
        {
            return ambitoFieldSpecified;
        }

        set
        {
            ambitoFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://www.sat.gob.mx/ine")]
public partial class INEEntidadContabilidad
{
    private int idContabilidadField;

    /// <comentarios/>
    [XmlAttribute()]
    public int IdContabilidad
    {
        get
        {
            return idContabilidadField;
        }

        set
        {
            idContabilidadField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[XmlType(Namespace = "http://www.sat.gob.mx/ine")]
public enum t_ClaveEntidad
{

    /// <comentarios/>
    AGU,

    /// <comentarios/>
    BCN,

    /// <comentarios/>
    BCS,

    /// <comentarios/>
    CAM,

    /// <comentarios/>
    CHP,

    /// <comentarios/>
    CHH,

    /// <comentarios/>
    COA,

    /// <comentarios/>
    COL,

    /// <comentarios/>
    DIF,

    /// <comentarios/>
    DUR,

    /// <comentarios/>
    GUA,

    /// <comentarios/>
    GRO,

    /// <comentarios/>
    HID,

    /// <comentarios/>
    JAL,

    /// <comentarios/>
    MEX,

    /// <comentarios/>
    MIC,

    /// <comentarios/>
    MOR,

    /// <comentarios/>
    NAY,

    /// <comentarios/>
    NLE,

    /// <comentarios/>
    OAX,

    /// <comentarios/>
    PUE,

    /// <comentarios/>
    QTO,

    /// <comentarios/>
    ROO,

    /// <comentarios/>
    SLP,

    /// <comentarios/>
    SIN,

    /// <comentarios/>
    SON,

    /// <comentarios/>
    TAB,

    /// <comentarios/>
    TAM,

    /// <comentarios/>
    TLA,

    /// <comentarios/>
    VER,

    /// <comentarios/>
    YUC,

    /// <comentarios/>
    ZAC
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[XmlType(Namespace = "http://www.sat.gob.mx/ine")]
public enum INEEntidadAmbito
{

    /// <comentarios/>
    Local,

    /// <comentarios/>
    Federal
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[XmlType(Namespace = "http://www.sat.gob.mx/ine")]
public enum INETipoProceso
{

    /// <comentarios/>
    Ordinario,

    /// <comentarios/>
    [XmlEnum("Precampaña")]
    Precampana,

    /// <comentarios/>
    [XmlEnum("Campaña")]
    Campana
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[XmlType(Namespace = "http://www.sat.gob.mx/ine")]
public enum INETipoComite
{

    /// <comentarios/>
    [XmlEnum("Ejecutivo Nacional")]
    EjecutivoNacional,

    /// <comentarios/>
    [XmlEnum("Ejecutivo Estatal")]
    EjecutivoEstatal,


    /// <comentarios/>
    [XmlEnum("Directivo Estatal")]
    DirectivoEstatal
}