//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimbradorCFDI2020.WSDiverza52 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.buzonfiscal.com/bf/ws/bfcorp/32", ConfigurationName="WSDiverza52.BuzonFiscalCorporativoPort")]
    public interface BuzonFiscalCorporativoPort {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación generaCFDi no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.buzonfiscal.com/CorporativoWS3.1/generaCFDi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TimbradorCFDI2020.WSDiverza52.generaCFDiResponse generaCFDi(TimbradorCFDI2020.WSDiverza52.generaCFDiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.buzonfiscal.com/CorporativoWS3.1/generaCFDi", ReplyAction="*")]
        System.Threading.Tasks.Task<TimbradorCFDI2020.WSDiverza52.generaCFDiResponse> generaCFDiAsync(TimbradorCFDI2020.WSDiverza52.generaCFDiRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación cancelaCFDi no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.buzonfiscal.com/CorporativoWS3.1/cancelaCFDi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TimbradorCFDI2020.WSDiverza52.cancelaCFDiResponse cancelaCFDi(TimbradorCFDI2020.WSDiverza52.cancelaCFDiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.buzonfiscal.com/CorporativoWS3.1/cancelaCFDi", ReplyAction="*")]
        System.Threading.Tasks.Task<TimbradorCFDI2020.WSDiverza52.cancelaCFDiResponse> cancelaCFDiAsync(TimbradorCFDI2020.WSDiverza52.cancelaCFDiRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/bfcorp/32")]
    public partial class RequestGeneraCFDiType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InfoBasicaComplexType infoBasicaField;
        
        private DocumentoType documentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/remision/52", Order=0)]
        public InfoBasicaComplexType InfoBasica {
            get {
                return this.infoBasicaField;
            }
            set {
                this.infoBasicaField = value;
                this.RaisePropertyChanged("InfoBasica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/RequestGeneraCFDI", Order=1)]
        public DocumentoType Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("Documento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/remision/52")]
    public partial class InfoBasicaComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InfoEspecialComplexType[] infoEspecialField;
        
        private string rfcEmisorField;
        
        private string rfcReceptorField;
        
        private string rfcSolicitanteField;
        
        private string serieField;
        
        private string aliasSucursalField;
        
        private string refIDField;
        
        private string folioField;
        
        private bool asignaFolioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InfoEspecial", Order=0)]
        public InfoEspecialComplexType[] InfoEspecial {
            get {
                return this.infoEspecialField;
            }
            set {
                this.infoEspecialField = value;
                this.RaisePropertyChanged("InfoEspecial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rfcEmisor {
            get {
                return this.rfcEmisorField;
            }
            set {
                this.rfcEmisorField = value;
                this.RaisePropertyChanged("rfcEmisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rfcReceptor {
            get {
                return this.rfcReceptorField;
            }
            set {
                this.rfcReceptorField = value;
                this.RaisePropertyChanged("rfcReceptor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rfcSolicitante {
            get {
                return this.rfcSolicitanteField;
            }
            set {
                this.rfcSolicitanteField = value;
                this.RaisePropertyChanged("rfcSolicitante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("serie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string aliasSucursal {
            get {
                return this.aliasSucursalField;
            }
            set {
                this.aliasSucursalField = value;
                this.RaisePropertyChanged("aliasSucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string refID {
            get {
                return this.refIDField;
            }
            set {
                this.refIDField = value;
                this.RaisePropertyChanged("refID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
                this.RaisePropertyChanged("folio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool asignaFolio {
            get {
                return this.asignaFolioField;
            }
            set {
                this.asignaFolioField = value;
                this.RaisePropertyChanged("asignaFolio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/remision/52")]
    public partial class InfoEspecialComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string atributoField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string atributo {
            get {
                return this.atributoField;
            }
            set {
                this.atributoField = value;
                this.RaisePropertyChanged("atributo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/bfcorp/32")]
    public partial class ResponseCancelaCFDiType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Result resultField;
        
        private bool canceledField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.buzonfiscal.com/ns/bf/conector/1", Order=0)]
        public Result Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool canceled {
            get {
                return this.canceledField;
            }
            set {
                this.canceledField = value;
                this.RaisePropertyChanged("canceled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.buzonfiscal.com/ns/bf/conector/1")]
    public partial class Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private messageType[] messageField;
        
        private int versionField;
        
        public Result() {
            this.versionField = 1;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Message", Order=0)]
        public messageType[] Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/bf/conector/1")]
    public partial class messageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private string fileField;
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
                this.RaisePropertyChanged("file");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/bfcorp/32")]
    public partial class RequestCancelaCFDiType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rfcEmisorField;
        
        private string rfcReceptorField;
        
        private string uuidField;
        
        private string refIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rfcEmisor {
            get {
                return this.rfcEmisorField;
            }
            set {
                this.rfcEmisorField = value;
                this.RaisePropertyChanged("rfcEmisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rfcReceptor {
            get {
                return this.rfcReceptorField;
            }
            set {
                this.rfcReceptorField = value;
                this.RaisePropertyChanged("rfcReceptor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string refID {
            get {
                return this.refIDField;
            }
            set {
                this.refIDField = value;
                this.RaisePropertyChanged("refID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/bfcorp/32")]
    public partial class InfoCFDiComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InfoEspecialComplexType[] infoEspecialField;
        
        private string serieField;
        
        private long folioField;
        
        private System.DateTime fechaField;
        
        private string selloField;
        
        private string noCertificadoField;
        
        private byte[] archivoField;
        
        private InfoCFDiComplexTypeTipo tipoField;
        
        private string versionField;
        
        private string uuidField;
        
        private byte[] qrField;
        
        private System.DateTime fechaTimbradoField;
        
        private bool fechaTimbradoFieldSpecified;
        
        private string refIdField;
        
        private string noCertificadoSATField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InfoEspecial", Namespace="http://www.buzonfiscal.com/ns/xsd/bf/remision/52", Order=0)]
        public InfoEspecialComplexType[] InfoEspecial {
            get {
                return this.infoEspecialField;
            }
            set {
                this.infoEspecialField = value;
                this.RaisePropertyChanged("InfoEspecial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("serie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
                this.RaisePropertyChanged("folio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sello {
            get {
                return this.selloField;
            }
            set {
                this.selloField = value;
                this.RaisePropertyChanged("sello");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string noCertificado {
            get {
                return this.noCertificadoField;
            }
            set {
                this.noCertificadoField = value;
                this.RaisePropertyChanged("noCertificado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
                this.RaisePropertyChanged("archivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public InfoCFDiComplexTypeTipo tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] qr {
            get {
                return this.qrField;
            }
            set {
                this.qrField = value;
                this.RaisePropertyChanged("qr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime fechaTimbrado {
            get {
                return this.fechaTimbradoField;
            }
            set {
                this.fechaTimbradoField = value;
                this.RaisePropertyChanged("fechaTimbrado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaTimbradoSpecified {
            get {
                return this.fechaTimbradoFieldSpecified;
            }
            set {
                this.fechaTimbradoFieldSpecified = value;
                this.RaisePropertyChanged("fechaTimbradoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string refId {
            get {
                return this.refIdField;
            }
            set {
                this.refIdField = value;
                this.RaisePropertyChanged("refId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string noCertificadoSAT {
            get {
                return this.noCertificadoSATField;
            }
            set {
                this.noCertificadoSATField = value;
                this.RaisePropertyChanged("noCertificadoSAT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.buzonfiscal.com/ns/xsd/bf/bfcorp/32")]
    public enum InfoCFDiComplexTypeTipo {
        
        /// <remarks/>
        XML,
        
        /// <remarks/>
        ZIP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/bfcorp/32")]
    public partial class ResponseGeneraCFDiType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Result resultField;
        
        private InfoCFDiComplexType infoCFDiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.buzonfiscal.com/ns/bf/conector/1", Order=0)]
        public Result Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public InfoCFDiComplexType InfoCFDi {
            get {
                return this.infoCFDiField;
            }
            set {
                this.infoCFDiField = value;
                this.RaisePropertyChanged("InfoCFDi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/RequestGeneraCFDI")]
    public partial class DocumentoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] archivoField;
        
        private string nombreArchivoField;
        
        private DocumentoTypeTipo tipoField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] Archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
                this.RaisePropertyChanged("Archivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NombreArchivo {
            get {
                return this.nombreArchivoField;
            }
            set {
                this.nombreArchivoField = value;
                this.RaisePropertyChanged("NombreArchivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentoTypeTipo Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.buzonfiscal.com/ns/xsd/bf/RequestGeneraCFDI")]
    public enum DocumentoTypeTipo {
        
        /// <remarks/>
        ZIP,
        
        /// <remarks/>
        XML,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generaCFDiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/bfcorp/32", Order=0)]
        public TimbradorCFDI2020.WSDiverza52.RequestGeneraCFDiType RequestGeneraCFDi;
        
        public generaCFDiRequest() {
        }
        
        public generaCFDiRequest(TimbradorCFDI2020.WSDiverza52.RequestGeneraCFDiType RequestGeneraCFDi) {
            this.RequestGeneraCFDi = RequestGeneraCFDi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generaCFDiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/bfcorp/32", Order=0)]
        public TimbradorCFDI2020.WSDiverza52.ResponseGeneraCFDiType ResponseGeneraCFDi;
        
        public generaCFDiResponse() {
        }
        
        public generaCFDiResponse(TimbradorCFDI2020.WSDiverza52.ResponseGeneraCFDiType ResponseGeneraCFDi) {
            this.ResponseGeneraCFDi = ResponseGeneraCFDi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelaCFDiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/bfcorp/32", Order=0)]
        public TimbradorCFDI2020.WSDiverza52.RequestCancelaCFDiType RequestCancelaCFDi;
        
        public cancelaCFDiRequest() {
        }
        
        public cancelaCFDiRequest(TimbradorCFDI2020.WSDiverza52.RequestCancelaCFDiType RequestCancelaCFDi) {
            this.RequestCancelaCFDi = RequestCancelaCFDi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelaCFDiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/bfcorp/32", Order=0)]
        public TimbradorCFDI2020.WSDiverza52.ResponseCancelaCFDiType ResponseCancelaCFDi;
        
        public cancelaCFDiResponse() {
        }
        
        public cancelaCFDiResponse(TimbradorCFDI2020.WSDiverza52.ResponseCancelaCFDiType ResponseCancelaCFDi) {
            this.ResponseCancelaCFDi = ResponseCancelaCFDi;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BuzonFiscalCorporativoPortChannel : TimbradorCFDI2020.WSDiverza52.BuzonFiscalCorporativoPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BuzonFiscalCorporativoPortClient : System.ServiceModel.ClientBase<TimbradorCFDI2020.WSDiverza52.BuzonFiscalCorporativoPort>, TimbradorCFDI2020.WSDiverza52.BuzonFiscalCorporativoPort {
        
        public BuzonFiscalCorporativoPortClient() {
        }
        
        public BuzonFiscalCorporativoPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BuzonFiscalCorporativoPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuzonFiscalCorporativoPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuzonFiscalCorporativoPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TimbradorCFDI2020.WSDiverza52.generaCFDiResponse TimbradorCFDI2020.WSDiverza52.BuzonFiscalCorporativoPort.generaCFDi(TimbradorCFDI2020.WSDiverza52.generaCFDiRequest request) {
            return base.Channel.generaCFDi(request);
        }
        
        public TimbradorCFDI2020.WSDiverza52.ResponseGeneraCFDiType generaCFDi(TimbradorCFDI2020.WSDiverza52.RequestGeneraCFDiType RequestGeneraCFDi) {
            TimbradorCFDI2020.WSDiverza52.generaCFDiRequest inValue = new TimbradorCFDI2020.WSDiverza52.generaCFDiRequest();
            inValue.RequestGeneraCFDi = RequestGeneraCFDi;
            TimbradorCFDI2020.WSDiverza52.generaCFDiResponse retVal = ((TimbradorCFDI2020.WSDiverza52.BuzonFiscalCorporativoPort)(this)).generaCFDi(inValue);
            return retVal.ResponseGeneraCFDi;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TimbradorCFDI2020.WSDiverza52.generaCFDiResponse> TimbradorCFDI2020.WSDiverza52.BuzonFiscalCorporativoPort.generaCFDiAsync(TimbradorCFDI2020.WSDiverza52.generaCFDiRequest request) {
            return base.Channel.generaCFDiAsync(request);
        }
        
        public System.Threading.Tasks.Task<TimbradorCFDI2020.WSDiverza52.generaCFDiResponse> generaCFDiAsync(TimbradorCFDI2020.WSDiverza52.RequestGeneraCFDiType RequestGeneraCFDi) {
            TimbradorCFDI2020.WSDiverza52.generaCFDiRequest inValue = new TimbradorCFDI2020.WSDiverza52.generaCFDiRequest();
            inValue.RequestGeneraCFDi = RequestGeneraCFDi;
            return ((TimbradorCFDI2020.WSDiverza52.BuzonFiscalCorporativoPort)(this)).generaCFDiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TimbradorCFDI2020.WSDiverza52.cancelaCFDiResponse TimbradorCFDI2020.WSDiverza52.BuzonFiscalCorporativoPort.cancelaCFDi(TimbradorCFDI2020.WSDiverza52.cancelaCFDiRequest request) {
            return base.Channel.cancelaCFDi(request);
        }
        
        public TimbradorCFDI2020.WSDiverza52.ResponseCancelaCFDiType cancelaCFDi(TimbradorCFDI2020.WSDiverza52.RequestCancelaCFDiType RequestCancelaCFDi) {
            TimbradorCFDI2020.WSDiverza52.cancelaCFDiRequest inValue = new TimbradorCFDI2020.WSDiverza52.cancelaCFDiRequest();
            inValue.RequestCancelaCFDi = RequestCancelaCFDi;
            TimbradorCFDI2020.WSDiverza52.cancelaCFDiResponse retVal = ((TimbradorCFDI2020.WSDiverza52.BuzonFiscalCorporativoPort)(this)).cancelaCFDi(inValue);
            return retVal.ResponseCancelaCFDi;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TimbradorCFDI2020.WSDiverza52.cancelaCFDiResponse> TimbradorCFDI2020.WSDiverza52.BuzonFiscalCorporativoPort.cancelaCFDiAsync(TimbradorCFDI2020.WSDiverza52.cancelaCFDiRequest request) {
            return base.Channel.cancelaCFDiAsync(request);
        }
        
        public System.Threading.Tasks.Task<TimbradorCFDI2020.WSDiverza52.cancelaCFDiResponse> cancelaCFDiAsync(TimbradorCFDI2020.WSDiverza52.RequestCancelaCFDiType RequestCancelaCFDi) {
            TimbradorCFDI2020.WSDiverza52.cancelaCFDiRequest inValue = new TimbradorCFDI2020.WSDiverza52.cancelaCFDiRequest();
            inValue.RequestCancelaCFDi = RequestCancelaCFDi;
            return ((TimbradorCFDI2020.WSDiverza52.BuzonFiscalCorporativoPort)(this)).cancelaCFDiAsync(inValue);
        }
    }
}
