// ------------------------------------------------------------------------------
// <auto-generated>
// Este código fue generado por una herramienta.
// Versión del motor en tiempo de ejecución:2.0.50727.5485
// 
// Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
// se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=2.0.50727.3038.
// 

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://www.diverza.com/ns/addenda/diverza/1")]
[XmlRoot(Namespace = "http://www.diverza.com/ns/addenda/diverza/1", IsNullable = false)]
public partial class diverza
{
    private diverzaGenerales generalesField;
    private diverzaClavesDescripcion clavesDescripcionField;
    private diverzaEmisor emisorField;
    private diverzaReceptor receptorField;
    private diverzaConceptos conceptosField;
    private extra[] complementoField;
    private string versionField;

    public diverza() : base()
    {
        versionField = "1.1";
    }

    /// <comentarios/>
    public diverzaGenerales generales
    {
        get
        {
            return generalesField;
        }

        set
        {
            generalesField = value;
        }
    }

    /// <comentarios/>
    public diverzaClavesDescripcion clavesDescripcion
    {
        get
        {
            return clavesDescripcionField;
        }

        set
        {
            clavesDescripcionField = value;
        }
    }

    /// <comentarios/>
    public diverzaEmisor emisor
    {
        get
        {
            return emisorField;
        }

        set
        {
            emisorField = value;
        }
    }

    /// <comentarios/>
    public diverzaReceptor receptor
    {
        get
        {
            return receptorField;
        }

        set
        {
            receptorField = value;
        }
    }

    /// <comentarios/>
    public diverzaConceptos conceptos
    {
        get
        {
            return conceptosField;
        }

        set
        {
            conceptosField = value;
        }
    }

    /// <comentarios/>
    [XmlArrayItem("datosExtra", IsNullable = false)]
    public extra[] complemento
    {
        get
        {
            return complementoField;
        }

        set
        {
            complementoField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string version
    {
        get
        {
            return versionField;
        }

        set
        {
            versionField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://www.diverza.com/ns/addenda/diverza/1")]
public partial class diverzaGenerales
{
    private string tipoDocumentoField;
    private string totalConLetraField;
    private string observacionesField;
    private string numeroOrdenField;
    private string nombreTransportistaField;
    private string numeroEntregaField;
    private string terminosPagoField;
    private DateTime fechaEntregaField;
    private bool fechaEntregaFieldSpecified;
    private DateTime fechaTipoCambioField;
    private bool fechaTipoCambioFieldSpecified;

    /// <comentarios/>
    [XmlAttribute()]
    public string tipoDocumento
    {
        get
        {
            return tipoDocumentoField;
        }

        set
        {
            tipoDocumentoField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string totalConLetra
    {
        get
        {
            return totalConLetraField;
        }

        set
        {
            totalConLetraField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string observaciones
    {
        get
        {
            return observacionesField;
        }

        set
        {
            observacionesField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string numeroOrden
    {
        get
        {
            return numeroOrdenField;
        }

        set
        {
            numeroOrdenField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string nombreTransportista
    {
        get
        {
            return nombreTransportistaField;
        }

        set
        {
            nombreTransportistaField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string numeroEntrega
    {
        get
        {
            return numeroEntregaField;
        }

        set
        {
            numeroEntregaField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string terminosPago
    {
        get
        {
            return terminosPagoField;
        }

        set
        {
            terminosPagoField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute(DataType = "date")]
    public DateTime fechaEntrega
    {
        get
        {
            return fechaEntregaField;
        }

        set
        {
            fechaEntregaField = value;
        }
    }

    /// <comentarios/>
    [XmlIgnore()]
    public bool fechaEntregaSpecified
    {
        get
        {
            return fechaEntregaFieldSpecified;
        }

        set
        {
            fechaEntregaFieldSpecified = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute(DataType = "date")]
    public DateTime fechaTipoCambio
    {
        get
        {
            return fechaTipoCambioField;
        }

        set
        {
            fechaTipoCambioField = value;
        }
    }

    /// <comentarios/>
    [XmlIgnore()]
    public bool fechaTipoCambioSpecified
    {
        get
        {
            return fechaTipoCambioFieldSpecified;
        }

        set
        {
            fechaTipoCambioFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.diverza.com/ns/addenda/diverza/1")]
public partial class extra
{
    private string indicadorField;
    private string atributoField;
    private string valorField;
    private string prefijoField;
    private string sufijoField;

    /// <comentarios/>
    [XmlAttribute()]
    public string indicador
    {
        get
        {
            return indicadorField;
        }

        set
        {
            indicadorField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string atributo
    {
        get
        {
            return atributoField;
        }

        set
        {
            atributoField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string valor
    {
        get
        {
            return valorField;
        }

        set
        {
            valorField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string prefijo
    {
        get
        {
            return prefijoField;
        }

        set
        {
            prefijoField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string sufijo
    {
        get
        {
            return sufijoField;
        }

        set
        {
            sufijoField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.diverza.com/ns/addenda/diverza/1")]
public partial class ubicacion
{
    private string codigoSitioField;
    private string calleField;
    private string numeroField;
    private string coloniaField;
    private string ciudadField;
    private string municipioField;
    private string estadoField;
    private string paisField;
    private string codigoPostalField;

    /// <comentarios/>
    [XmlAttribute()]
    public string codigoSitio
    {
        get
        {
            return codigoSitioField;
        }

        set
        {
            codigoSitioField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string calle
    {
        get
        {
            return calleField;
        }

        set
        {
            calleField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string numero
    {
        get
        {
            return numeroField;
        }

        set
        {
            numeroField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string colonia
    {
        get
        {
            return coloniaField;
        }

        set
        {
            coloniaField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string ciudad
    {
        get
        {
            return ciudadField;
        }

        set
        {
            ciudadField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string municipio
    {
        get
        {
            return municipioField;
        }

        set
        {
            municipioField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string estado
    {
        get
        {
            return estadoField;
        }

        set
        {
            estadoField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string pais
    {
        get
        {
            return paisField;
        }

        set
        {
            paisField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string codigoPostal
    {
        get
        {
            return codigoPostalField;
        }

        set
        {
            codigoPostalField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.diverza.com/ns/addenda/diverza/1")]
public partial class datos_Contacto
{
    private string telefonoField;
    //private string emailComercialField;
    //private string emailContactoField;
    private string webField;

    /// <comentarios/>
    [XmlAttribute()]
    public string telefono
    {
        get
        {
            return telefonoField;
        }

        set
        {
            telefonoField = value;
        }
    }

    /// <comentarios/>
    //[XmlAttribute()]
    //public string emailComercial
    //{
    //    get
    //    {
    //        return emailComercialField;
    //    }

    //    set
    //    {
    //        emailComercialField = value;
    //    }
    //}

    ///// <comentarios/>
    //[XmlAttribute()]
    //public string emailContacto
    //{
    //    get
    //    {
    //        return emailContactoField;
    //    }

    //    set
    //    {
    //        emailContactoField = value;
    //    }
    //}

    /// <comentarios/>
    [XmlAttribute()]
    public string web
    {
        get
        {
            return webField;
        }

        set
        {
            webField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://www.diverza.com/ns/addenda/diverza/1")]
public partial class diverzaClavesDescripcion
{
    private string c_FormaPagoField;
    private string c_MonedaField;
    private string c_TipoDeComprobanteField;
    private string c_MetodoPagoField;
    private string c_LugarExpedicionField;
    private string c_TipoRelacionField;
    private string c_RegimenFiscalField;
    private string c_ResidenciaFiscalField;
    private string c_UsoCFDIField;

    /// <comentarios/>
    [XmlAttribute()]
    public string c_FormaPago
    {
        get
        {
            return c_FormaPagoField;
        }

        set
        {
            c_FormaPagoField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string c_Moneda
    {
        get
        {
            return c_MonedaField;
        }

        set
        {
            c_MonedaField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string c_TipoDeComprobante
    {
        get
        {
            return c_TipoDeComprobanteField;
        }

        set
        {
            c_TipoDeComprobanteField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string c_MetodoPago
    {
        get
        {
            return c_MetodoPagoField;
        }

        set
        {
            c_MetodoPagoField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string c_LugarExpedicion
    {
        get
        {
            return c_LugarExpedicionField;
        }

        set
        {
            c_LugarExpedicionField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string c_TipoRelacion
    {
        get
        {
            return c_TipoRelacionField;
        }

        set
        {
            c_TipoRelacionField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string c_RegimenFiscal
    {
        get
        {
            return c_RegimenFiscalField;
        }

        set
        {
            c_RegimenFiscalField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string c_ResidenciaFiscal
    {
        get
        {
            return c_ResidenciaFiscalField;
        }

        set
        {
            c_ResidenciaFiscalField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string c_UsoCFDI
    {
        get
        {
            return c_UsoCFDIField;
        }

        set
        {
            c_UsoCFDIField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://www.diverza.com/ns/addenda/diverza/1")]
public partial class diverzaEmisor
{
    private datos_Contacto datosContactoEField;
    private ubicacion domicilioFiscalEField;
    private diverzaEmisorSucursalE sucursalEField;
    //private string vendedorField;
    private string numeroProveedorField;
    private string tipoProveedorField;
    private string glnField;

    /// <comentarios/>
    public datos_Contacto datosContactoE
    {
        get
        {
            return datosContactoEField;
        }

        set
        {
            datosContactoEField = value;
        }
    }

    /// <comentarios/>
    public ubicacion domicilioFiscalE
    {
        get
        {
            return domicilioFiscalEField;
        }

        set
        {
            domicilioFiscalEField = value;
        }
    }

    /// <comentarios/>
    public diverzaEmisorSucursalE sucursalE
    {
        get
        {
            return sucursalEField;
        }

        set
        {
            sucursalEField = value;
        }
    }

    /// <comentarios/>
    //[XmlAttribute()]
    //public string vendedor
    //{
    //    get
    //    {
    //        return vendedorField;
    //    }

    //    set
    //    {
    //        vendedorField = value;
    //    }
    //}

    /// <comentarios/>
    [XmlAttribute()]
    public string numeroProveedor
    {
        get
        {
            return numeroProveedorField;
        }

        set
        {
            numeroProveedorField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string tipoProveedor
    {
        get
        {
            return tipoProveedorField;
        }

        set
        {
            tipoProveedorField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string gln
    {
        get
        {
            return glnField;
        }

        set
        {
            glnField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://www.diverza.com/ns/addenda/diverza/1")]
public partial class diverzaEmisorSucursalE
{
    private ubicacion domicilioSucursalField;
    private datos_Contacto datosContactoField;
    private string aliasField;

    /// <comentarios/>
    public ubicacion domicilioSucursal
    {
        get
        {
            return domicilioSucursalField;
        }

        set
        {
            domicilioSucursalField = value;
        }
    }

    /// <comentarios/>
    public datos_Contacto datosContacto
    {
        get
        {
            return datosContactoField;
        }

        set
        {
            datosContactoField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string alias
    {
        get
        {
            return aliasField;
        }

        set
        {
            aliasField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://www.diverza.com/ns/addenda/diverza/1")]
public partial class diverzaReceptor
{
    private datos_Contacto datosContactoRField;
    private ubicacion domicilioFiscalRField;
    private ubicacion[] destinoField;
    private string numClienteField;

    /// <comentarios/>
    public datos_Contacto datosContactoR
    {
        get
        {
            return datosContactoRField;
        }

        set
        {
            datosContactoRField = value;
        }
    }

    /// <comentarios/>
    public ubicacion domicilioFiscalR
    {
        get
        {
            return domicilioFiscalRField;
        }

        set
        {
            domicilioFiscalRField = value;
        }
    }

    /// <comentarios/>
    [XmlArrayItem("domicilioDestinoR", IsNullable = false)]
    public ubicacion[] destino
    {
        get
        {
            return destinoField;
        }

        set
        {
            destinoField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string numCliente
    {
        get
        {
            return numClienteField;
        }

        set
        {
            numClienteField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://www.diverza.com/ns/addenda/diverza/1")]
public partial class diverzaConceptos
{
    private diverzaConceptosConcepto[] conceptoField;
    private string numeroConceptosField;

    /// <comentarios/>
    [XmlElement("concepto")]
    public diverzaConceptosConcepto[] concepto
    {
        get
        {
            return conceptoField;
        }

        set
        {
            conceptoField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute(DataType = "integer")]
    public string numeroConceptos
    {
        get
        {
            return numeroConceptosField;
        }

        set
        {
            numeroConceptosField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "2.0.50727.3038")]
[Serializable()]
[DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://www.diverza.com/ns/addenda/diverza/1")]
public partial class diverzaConceptosConcepto
{
    private extra[] datosExtraCField;
    private string indicadorField;
    private string identificador1Field;
    private string identificador2Field;
    private string descripcionExtranjeraField;
    private decimal valorUnitarioMonedaExtranjeraField;
    private bool valorUnitarioMonedaExtranjeraFieldSpecified;
    private decimal importeMonedaExtranjeraField;
    private bool importeMonedaExtranjeraFieldSpecified;
    private string mensajeField;
    private string unidadMedidaField;
    private string codigoEANField;
    private string skuField;
    private string nombreTransportistaCField;
    private string numeroEntregaCField;
    private DateTime fechaEntregaCField;
    private bool fechaEntregaCFieldSpecified;

    /// <comentarios/>
    [XmlElement("datosExtraC")]
    public extra[] datosExtraC
    {
        get
        {
            return datosExtraCField;
        }

        set
        {
            datosExtraCField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string indicador
    {
        get
        {
            return indicadorField;
        }

        set
        {
            indicadorField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string identificador1
    {
        get
        {
            return identificador1Field;
        }

        set
        {
            identificador1Field = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string identificador2
    {
        get
        {
            return identificador2Field;
        }

        set
        {
            identificador2Field = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string descripcionExtranjera
    {
        get
        {
            return descripcionExtranjeraField;
        }

        set
        {
            descripcionExtranjeraField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public decimal valorUnitarioMonedaExtranjera
    {
        get
        {
            return valorUnitarioMonedaExtranjeraField;
        }

        set
        {
            valorUnitarioMonedaExtranjeraField = value;
        }
    }

    /// <comentarios/>
    [XmlIgnore()]
    public bool valorUnitarioMonedaExtranjeraSpecified
    {
        get
        {
            return valorUnitarioMonedaExtranjeraFieldSpecified;
        }

        set
        {
            valorUnitarioMonedaExtranjeraFieldSpecified = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public decimal importeMonedaExtranjera
    {
        get
        {
            return importeMonedaExtranjeraField;
        }

        set
        {
            importeMonedaExtranjeraField = value;
        }
    }

    /// <comentarios/>
    [XmlIgnore()]
    public bool importeMonedaExtranjeraSpecified
    {
        get
        {
            return importeMonedaExtranjeraFieldSpecified;
        }

        set
        {
            importeMonedaExtranjeraFieldSpecified = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string mensaje
    {
        get
        {
            return mensajeField;
        }

        set
        {
            mensajeField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string unidadMedida
    {
        get
        {
            return unidadMedidaField;
        }

        set
        {
            unidadMedidaField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string codigoEAN
    {
        get
        {
            return codigoEANField;
        }

        set
        {
            codigoEANField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string sku
    {
        get
        {
            return skuField;
        }

        set
        {
            skuField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string nombreTransportistaC
    {
        get
        {
            return nombreTransportistaCField;
        }

        set
        {
            nombreTransportistaCField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute()]
    public string numeroEntregaC
    {
        get
        {
            return numeroEntregaCField;
        }

        set
        {
            numeroEntregaCField = value;
        }
    }

    /// <comentarios/>
    [XmlAttribute(DataType = "date")]
    public DateTime fechaEntregaC
    {
        get
        {
            return fechaEntregaCField;
        }

        set
        {
            fechaEntregaCField = value;
        }
    }

    /// <comentarios/>
    [XmlIgnore()]
    public bool fechaEntregaCSpecified
    {
        get
        {
            return fechaEntregaCFieldSpecified;
        }

        set
        {
            fechaEntregaCFieldSpecified = value;
        }
    }
}
